<!-- 에러에 대하여 -->
<!-- try catch를 쓰는 이유 : 혹시나 중요한 함수에 문제가 있나 알기 위해서 -->
<!-- 유튜브 강좌 : https://www.youtube.com/watch?v=lhtVqZvwzks -->

<!DOCTYPE html>
<html>

<head>
    <title>Document</title>
</head>

<body>
    <script>
        try {
            console.log("콘솔에 출력");
        } catch (error) {
            //에러를 잡아내겠다.
            //어떤 에러든 이 안에 넣으면 어떤 에러가 나는지 얘기해 주면서 코드가 실행이 된다. 
            console.log(error.name);
            console.log(error.message);

        }

        var x = 2;
        var y = 3;

        console.log(x + y);

        //

        //강제로 에러를 발생시키는 법
        try {
            if (x == 0) {
                throw "value is zero."; //throw를 만나면 무조건 catch 간다.
            }
        } catch (error) {
            console.log(error);
        } finally {
            console.log("try/catch를 모두 실행한 후 반드시 실행하는 부분");
        }
    </script>
</body>

</html>